JS.png : JS.eps
	convert JS.eps JS.png

erl_solutions_logo.png : erl_solutions_logo.eps
	convert -resize 234 erl_solutions_logo.eps erl_solutions_logo.png

IntelliFactory.png : IntelliFactory-logo.png
	convert -resize 450 IntelliFactory-logo.png IntelliFactory.png
